language: python
python:
  - "2.7"
  - "3.3"
before_install:
    - "pip install -r requirements.txt"
install:
  - python setup.py install
script:
  - cd tests && nosetests --verbose --nocapture test_plotting.py test_ctd.py test_processing.py
