language: python
python:
  - "2.7"
  - "3.3"
# Command to install dependencies.
virtualenv:
  system_site_packages: true
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
install:
    - pip install numpy
    - pip install scipy
    - pip install pandas
    - pip install matplotlib
    - pip install gsw
script:
    - cd tests
    - nosetests --verbose --nocapture
branches:
  only:
    - master
