language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_install:
    - ci/before_install.sh
    - pip install --use-mirrors gsw pandas matplotlib

install:
    - python setup.py install
script:
    - cd tests
    - nosetests --verbose --nocapture

branches:
  only:
    - master
