language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"

virtualenv:
  system_site_packages: true

before_install:
  - ci/before_install.sh
  - export DISPLAY=:99.0
  - pip install --use-mirrors numpy
  - pip install --use-mirrors scipy
  - pip install --use-mirrors matplotlib
  - pip install --use-mirrors pandas
  - pip install --use-mirrors gsw

install:
  - python setup.py install
script:
  - cd tests
  - nosetests --verbose --nocapture

branches:
  only:
    - master
