language: python
python:
  - "2.7"
  - "3.3"
# Command to install dependencies.
virtualenv:
  system_site_packages: true
before_install:
    - sudo apt-get update
    - sudo apt-get install -qq
    - sudo apt-get install -qq python-numpy python-scipy
    - sudo apt-get install -qq python3-numpy python3-scipy
install:
    - pip install numpy
    - pip install pandas
    - pip install matplotlib
    - pip install gsw
script:
    - cd tests
    - nosetests --verbose --nocapture
branches:
  only:
    - master
