language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.1"
  - "3.2"
# Command to install dependencies.
virtualenv:
  system_site_packages: true
before_install:
    - sudo apt-get install -qq python-numpy python-scipy
install:
    - pip install gsw
    - pip install pandas
    - pip install matplotlib
script: python tests/test_ctd.py
branches:
  only:
    - master
